### ISSUE TITLE
Dark mode input background is white

### ISSUE THREAD

**Issue by JHay0112** [JHay0112/lcadide#58]
In the dark mode the input box has a white background, the same colour as the input text. This is impossible to use and looks awful.

![image](https://user-images.githubusercontent.com/29882279/221731136-e16b26ad-e06b-4242-901e-e9ce2ddbf133.png)

**Comment by kaushikc44** [comment]
Can you please point out to the code where you using this box, the file and its location. Thanks

**Comment by JHay0112** [comment]
Kia ora @kaushikc44,

I believe the culprit is line 110 of src/ui/symbol.tsx (https://github.com/JHay0112/lcadide/blob/main/src/ui/symbol.tsx#L110).
This should be the input element that does not have the correct styling in dark mode.
Please note that we are using tailwind css in this project so the new styles should match this and the existing dark mode background styles as defined in the main css file.

Cheers for the interest.

**Comment by kaushikc44** [comment]
Hi I am unable to find the dark mode or  the Input box

**Comment by JHay0112** [comment]
The input box should be at the line specified in my last comment. To make this properly behave with the dark mode you need to add `bg-primary` to the class attribute of the input box at the line specified. The `bg-primary` class is specified in `src/index.css`

If you wish to try out the website in dark mode you can either use the popup when the page first loads, or type `toggleTheme()` into the javascript console of your browser.

For testing whether the popup is as expected based on your changes you will need to place a component from the bottom toolbar and then right click  the placed component to open the context menu (as displayed in the screenshot of the issue), then select edit in the right toolbar of the context menu.

**Comment by JHay0112** [comment]
Hi @kaushikc44 just wondering how you have got on with this?
