### ISSUE TITLE
Feature request: Keybinds

### ISSUE THREAD

**Issue by captvansciencypants** [JHay0112/lcadide#63]
W for wire!
R for resistor! :D

**Comment by JHay0112** [comment]
I am very keen on adding these, going back to the toolbar all the time is a right pain. This is a priority.

**Comment by JHay0112** [comment]
An experimental version of this has been implemented in the keybinds branch. Unfortunately there is a conflict between using "r" for resistor and "r" for rotate. 

A potential solution could be that "r" for rotate still applies, but only when a component is being grabbed... This will require a slightly more complex solution than is currently implemented.

**Comment by JHay0112** [comment]
As a temporary solution the "z" key has been chosen as an alternative rotate key.

**Comment by JHay0112** [comment]
This is being closed as the keybinds have been merged into main and deployed (#64). #65 and #66 have been created with respect to consequences of #64, in particular #66 considers alternative rotate key setups.
